#!/usr/bin/env python3
"""Generate Verilog lookup-table assignments used by the RTL encoder."""

from __future__ import annotations

import re
from pathlib import Path


INTERLEAVERS = [
    [
        5, 39, 18, 47, 6, 45, 21, 50, 4, 40, 30, 55, 1, 46, 22, 54,
        0, 42, 27, 61, 7, 43, 29, 60, 12, 37, 20, 51, 14, 35, 25, 52,
        3, 44, 16, 56, 10, 32, 23, 49, 13, 41, 28, 58, 9, 31, 26, 53,
        15, 38, 17, 48, 11, 36, 24, 57, 2, 33, 19, 59, 8, 34,
    ],
    [
        5, 36, 21, 49, 4, 37, 20, 52, 14, 35, 27, 61, 2, 32, 28, 53,
        7, 31, 17, 58, 3, 38, 26, 60, 11, 43, 16, 51, 8, 45, 25, 56,
        12, 34, 19, 47, 13, 41, 24, 54, 10, 44, 22, 59, 1, 40, 23, 57,
        0, 46, 18, 48, 6, 42, 29, 55, 15, 33, 30, 50, 9, 39,
    ],
    [
        8, 36, 16, 52, 14, 35, 19, 51, 9, 45, 24, 58, 15, 33, 23, 59,
        11, 38, 30, 48, 12, 34, 29, 57, 6, 42, 20, 47, 4, 39, 21, 56,
        13, 43, 25, 50, 1, 44, 18, 55, 10, 41, 27, 53, 0, 32, 22, 54,
        7, 31, 17, 49, 5, 37, 26, 60, 2, 46, 28, 61, 3, 40,
    ],
]


def parse_c1_sequence(path: Path) -> list[int]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"kPolarReliabilitySequenceC1\s*=\s*\{(.*?)\};", text, re.S)
    if not match:
        raise RuntimeError("Could not locate kPolarReliabilitySequenceC1")
    values = [int(item) for item in re.findall(r"\d+", match.group(1))]
    if len(values) != 8192:
        raise RuntimeError(f"Expected 8192 C.1 values, got {len(values)}")
    if set(values) != set(range(8192)):
        raise RuntimeError("C.1 values are not a complete 0..8191 permutation")
    return values


def main() -> None:
    c1 = parse_c1_sequence(Path("src/polar_reliability_sequence.cpp"))
    q1024 = [value for value in c1 if value < 1024]
    if len(q1024) != 1024:
        raise RuntimeError(f"Expected 1024 Q_1024 values, got {len(q1024)}")
    if set(q1024) != set(range(1024)):
        raise RuntimeError("Q_1024 is not a complete 0..1023 permutation")
    for seq in INTERLEAVERS:
        if sorted(seq) != list(range(62)):
            raise RuntimeError("Interleaver sequence is not a 0..61 permutation")

    lines = [
        "// Generated by scripts/generate_rtl_tables.py. Do not edit by hand.",
        "// Contains Table C.1-derived Q_1024 and the fixed channel interleaver tables.",
    ]
    for idx, value in enumerate(q1024):
        lines.append(f"rel_q[{idx:4d}] = 10'd{value};")
    for seq_idx, seq in enumerate(INTERLEAVERS):
        for col, value in enumerate(seq):
            lines.append(f"iseq{seq_idx}[{col:2d}] = 6'd{value};")

    Path("rtl/slb_polar_tables.vh").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
